### ISSUE TITLE
ParserError Unexpected token at Launch Project

### ISSUE THREAD

**Issue by milen-prg** [solar2d/Solar2DEditor-VSCode#1]
Windows 10 Pro 64bit

At try command Solar2D: Launch Project, the result is:

PS C:\Users\muser\Documents\Work\solar2ds\p1> "C:Program FilesCorona LabsCoronaCorona Simulator.exe" "/c:/Users/muser/Documents/Work/solar2ds/p1" /no-console /debug
ParserError: 
Line |
   1 |  … ulator.exe" "/c:/Users/muser/Documents/Work/solar2ds/p1" /n …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Unexpected token '"/c:/Users/muser/Documents/Work/solar2ds/p1"' in expression or statement.

The command inserted manually in windows console works:
"C:\Program Files (x86)\Corona Labs\Corona\Corona Simulator.exe" "C:\Users\muser\Documents\Work\solar2ds\p1" /debug

**Comment by scottrules44** [comment]
This should be fixed with 1.1.5, thanks for reporting
